services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hnim-mssql
    restart: always
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - ./data/mssql:/var/opt/mssql
    labels:
      - "casaos.icon=https://github.com/Kompetankedi/HNIM/blob/main/hnim(1).png?raw=true
      - "casaos.title=HNIM MSSQL"

  backend:
    image: kompetankedi/hnim-backend:latest
    container_name: hnim-backend
    restart: always
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - DB_HOST=mssql
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
    depends_on:
      - mssql
    labels:
      - "casaos.icon=https://github.com/Kompetankedi/HNIM/blob/main/hnim(1).png?raw=true
      - "casaos.title=HNIM Backend"

volumes:
  mssql_data:
