services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hnim-mssql
    restart: always
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - ./data/mssql:/var/opt/mssql
    labels:
      - "casaos.icon=https://raw.githubusercontent.com/IceWhaleTech/CasaOS-AppStore/main/Apps/MSSQL/icon.png"
      - "casaos.title=HNIM MSSQL"

  backend:
    image: kompetankedi/hnim-backend:latest
    container_name: hnim-backend
    restart: always
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - DB_HOST=mssql
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
    depends_on:
      - mssql
    labels:
      - "casaos.icon=https://img.icons8.com/fluent/1200/node-js.jpg"
      - "casaos.title=HNIM Backend"

volumes:
  mssql_data:
